### ISSUE TITLE
Adding effects :  "green screen" and "colorfull stripes" artefacts

### ISSUE THREAD

**Issue by d-j-a-y** [c0ntrol/veejay#11] opened 2015-10-06 14:20 UTC
A lot of effects produce greeny output 
* Alpha Luma overlay
* Effect Border Translation
...

And some other colorfull stripes
* Blend by color key (RGB)
* Chameleon
* Crhoma Key (RGB)
* Bathroom window
...

Version infos :
* commit 0c8fbc12525720df9fd0cc1d36a5af4f1c21dd3f 
* avconv version 11-6:11-1

Sample infos :  
1. Stream #0.0: Video: mjpeg, yuvj420p, 800x600 [PAR 2937:2602 DAR 1958:1301], 25 fps, 25 tbn
2. Stream #0.0: Video: mjpeg, yuvj422p, 800x600 [PAR 2937:2602 DAR 1958:1301], 25 fps, 25 tbn
3. Stream #0.0: Video: rawvideo, yuv422p, 800x600, PAR 2937:2602 DAR 1958:1301, 25 fps, 25 tbn

Sample generation : 
1. avconv -f image2 -r 25 -i image-%04d.jpg -q:v 1 -vcodec mjpeg -s 800x600 output.avi
2. avconv -f image2 -r 25 -i image-%04d.jpg -q:v 1 -vcodec mjpeg -pix_fmt yuvj422p -s 800x600 output.avi
3. also with -vcodec rawvideo -pix_fmt yuv422p

**Comment by c0ntrol** [comment] 2015-10-06 17:03
Investigating issue using Ubuntu 14.10 (setting up environment)

**Comment by flvi0** [comment] 2015-10-06 17:42
Just want to say I can confirm the bug, had the same on gentoo. Don't have access to the machine now so I regret no further info. Didn't report back then since i thought it might be an error on my part.

**Comment by d-j-a-y** [comment] 2015-10-06 18:19
Same problem using ffmpeg version 2.6.git.

I have regressed to 3f601e3669bddd794 , and there everything is fine (with ffmpeg version 2.6.git)

**Comment by c0ntrol** [comment] 2015-10-06 18:40
I don't think this problem is ffmpeg related

**Comment by d-j-a-y** [comment] 2015-10-06 19:26
agree ... that was the sense of my previous comment ;-)

**Comment by c0ntrol** [comment] 2015-10-06 19:45
Yes the first line confused me

1) Please add a screenshot of the artifacts you are seeing

2) What memcpy() and memset() does veejay report it is using ?

    W: No plugins.cfg found (see DOC/HowtoPlugins)
    I: Using SIMD MMX/MMX2/SSE optimized memcpy() v1
    I: Using SIMD MMX/MMX2/SSE optimized memset()
    D: Registered 219 VIMS events

3) Does setting VEEJAY_MULTITHREAD_TASKS=0 make any difference?

    export VEEJAY_MULTITHREAD_TASKS=0


Reproducing here fails using Image: http://mars.nasa.gov/images/mars-globe-valles-marineris-enhanced-br2.jpg and your avconv commands

My guess is the artifacts are caused by an assembler optimized function ?



![issue11](https://cloud.githubusercontent.com/assets/7851900/10320215/abf21bbc-6c72-11e5-99f0-27443c8b29ef.png)

**Comment by d-j-a-y** [comment] 2015-10-06 21:38
The first line was not very clear
>My guess is the artifacts are caused by an assembler optimized function ?

Yep look like what you have already fixed before ... 

>2) What memcpy() and memset() does veejay report it is using ?

    configure:  Architecture: x86_64 
    configure: 
    configure:    x86  
    configure:     MMX     enabled     : yes
    configure:     MMX2    enabled     : yes
    configure:     SSE     enabled     : yes
    configure:     SSE2    enabled     : yes
    configure:     3DNOW   enabled     : no
    configure:     CMOV    enabled     : yes
    configure:     AVX     enabled     : yes
....

    I: Using SIMD SSE optimized memcpy() (64)
    I: Using SIMD glibc memset()

>3) Does setting VEEJAY_MULTITHREAD_TASKS=0 make any difference?

Nop 

![veejay-issue11](https://cloud.githubusercontent.com/assets/2943058/10323424/3f404d02-6c83-11e5-8292-602aacef6c01.png)

**Comment by c0ntrol** [comment] 2015-10-06 22:53
I have this now reproduced

The problem is with the compilation flags

If I set `-march=generic` instead of the auto-detected `-march=native` the problem is gone

This is set by ARCHFLAGS in configure.ac in combination with cpuinfo.sh

I will change this to default "generic" and fix the configure option --with-arch-target= so the user can choose a custom setting

I also found some problems with settings the CFLAGS that cause the particular artifact in your screenshot (libsubsample is affected) but more testing soon.

**Comment by c0ntrol** [comment] 2015-10-07 19:40
Should be fixed (verified on Ubuntu 14.10)

build and target current cpu-type:

    ./configure --without-libresample --with-arch-target=auto
    make && make install
    make clean 
    ldconfig

normal build:

    ./configure --without-libresample 
    make && make install
    make clean
    ldconfig

**Comment by d-j-a-y** [comment] 2015-10-07 22:42
artefacts fixed .... but .... now, 
* eats much more cpu (even doing "nothing") 
* video with effects look like have no synchro on vbl.

**Comment by c0ntrol** [comment] 2015-10-07 23:14
Please re-compile with --enable-debug and no --with-arch-target to see if the problems are related to this issue (if the problems are then gone, then they would be)

**Comment by d-j-a-y** [comment] 2015-10-08 08:43
builded with --enable-debug

I think i know now where the "vbl" problem come from : even at speed 1 / repeat 1, the videos are played too fast. The real length (en second) time is not "respected" . And it's even faster when the Effect chain is disabled.

Also still eat cpu

**Comment by c0ntrol** [comment] 2015-10-08 15:52
This behaviour is not reproducable on my Slackware box but it is on Ubuntu 14.10; Does veejay title bar say it is running in infinite framerate ? 

Meanwhile, I'll see if veejay can produce a proper error when this happens

**Comment by c0ntrol** [comment] 2015-10-08 16:57
oops

**Closed** 2015-10-08 17:01 UTC

**Comment by d-j-a-y** [comment] 2015-10-09 09:30
video with effects look like have no synchro on vbl.

_FIXED !_
