### ISSUE TITLE
Reading a pipe , if the pipe close : veejay stuck.

### ISSUE THREAD

**Issue by d-j-a-y** [c0ntrol/veejay#238] opened 2019-07-01 22:32 UTC
> E: [/tmp/tmpjh4_grf_/myfifo] There was an error retrieving the frame
> I: [/tmp/tmpjh4_grf_/myfifo] ... Waiting for thread to become ready
> 

Could the "Waiting for thread to become ready" could be done in a thread ? :-)

**Comment by c0ntrol** [comment] 2019-07-02 17:29
I cannot reproduce it using these steps:
1. cd /tmp
2. mkfifo stream.yuv
3. mplayer -vo yuv4mpeg /some/video.avi
4. veejay -a0 -v -d
5. reloaded -a -t default 
6. 'New Stream' from menu -> File/URL -> /tmp/stream.yuv [Try]
7. New Stream appears 
8. Stream is playing
9. Repeat: Stop Mplayer, Start Mplayer:


LOG:
$ export VEEJAY_AV_LOG=55



[rawvideo @ 0x7fffb400e240] PACKET SIZE: 884736, STRIDE: 1536
[rawvideo @ 0x7fffb400e240] PACKET SIZE: 884736, STRIDE: 1536
[rawvideo @ 0x7fffb400e240] PACKET SIZE: 884736, STRIDE: 1536
E: [/tmp/stream.yuv] There was an error retrieving the frame
[AVIOContext @ 0x7fffb4010c00] Statistics: 58393007 bytes read, 0 seeks
I: [/tmp/stream.yuv] ... Waiting for thread to become ready
[NULL @ 0x7fffb4000b80] Opening '/tmp/stream.yuv' for reading
[file @ 0x7fffb400c240] Setting default whitelist 'file,crypto'
[yuv4mpegpipe @ 0x7fffb4000b80] Format yuv4mpegpipe probed with size=2048 and score=100
[yuv4mpegpipe @ 0x7fffb4000b80] Before avformat_find_stream_info() pos: 35 bytes read:4131 seeks:0 nb_streams:1
[yuv4mpegpipe @ 0x7fffb4000b80] All info found
[yuv4mpegpipe @ 0x7fffb4000b80] After avformat_find_stream_info() pos: 884777 bytes read:884777 seeks:0 frames:1
D: FFmpeg: video stream 0, codec_id 13
[rawvideo @ 0x7fffb40113c0] PACKET SIZE: 884736, STRIDE: 1536
[rawvideo @ 0x7fffb40113c0] PACKET SIZE: 884736, STRIDE: 1536
...

**Comment by c0ntrol** [comment] 2019-07-05 15:48
Please try a more recent version of ffmpeg

**Comment by c0ntrol** [comment] 2019-07-05 20:40
Closing, this is not a veejay bug

**Closed by c0ntrol** 2019-07-05 20:40 UTC
Labels: bug, question, veejay
